[package]
name = "medea-compat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
str0m = { path = ".." }
tokio = { version = "1.32", features = ["full"] }
futures = "0.3"